name: common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Samuel Zuniga Vanoye <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  equatable: ^0.1.0
  bloc: ^0.12.0
  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.0.0
