name: angular_app
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Sam Zuniga <samuelzv@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_bloc: ^0.6.0
  angular_components: ^0.11.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21
  bloc: ^0.11.0
  common:
    path: ../common

dependency_overrides:
  package_resolver: 1.0.6

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
  sass_builder: ^2.1.2
